version: 2
jobs:
  build:
    working_directory: ~/circleci-build
    machine: true
    environment:
      USE_CCACHE: 1
      ANDROID_JACK_VM_ARGS: "-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx6G"
      WITH_SU: true
    steps:
      - checkout
      - restore_cache:
          key: lineageos-oneplus6
      - run:
          name: Prepare
          command: ./prepare.sh
      - run:
          name: Run build
          command: ./build.sh
          no_output_timeout: 60m
      - run:
          name: Deploy
          command: ./deploy.sh
      - save_cache:
          key: lineageos-oneplus6
          paths:
            - ~/.ccache
      - store_artifacts:
          path: release
          destination: out